In [14]:
import numpy as np
import matplotlib.pyplot as plt

# Load train and test data
train_data = np.load('train.npy')  # Load first three samples from train.npy
test_data = np.load('test.npy')    # Load first three samples from test.npy
labels=np.load('labels.npy')

print(test_data.shape)
print(train_data.shape)
print(labels.shape)
print(labels[1:])

(4094, 299)
(4094, 299)
(4094, 299)
[[1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [7]:
import numpy as np

# Load the existing labels.npy
labels = np.load('labels.npy')

# Determine the number of columns (samples) in the original labels array
num_samples = labels.shape[1]

# Create a new array of shape (4094, num_samples) to hold the new labels
new_labels = np.zeros((4094, num_samples))

# Iterate through each column in the original labels array
for i in range(num_samples):
    first_value = labels[0, i]
    new_labels[:, i] = first_value

# Ensure the new array is of the required shape (4094, 300)
new_labels = new_labels[:, :300]

# Save the new labels array to new_labels.npy
np.save('new_labels.npy', new_labels)

# Print shapes to verify
print("Original labels shape:", labels.shape)
print("New labels shape:", new_labels.shape)
print(new_labels)


Original labels shape: (298, 4095)
New labels shape: (4094, 300)
[[1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 ...
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]]
